CREATE DATABASE NHANTINHENHO
GO

USE NHANTINHENHO
GO

CREATE TABLE THONGTINDANGNHAP (
  ID_DangNhap INT PRIMARY KEY IDENTITY(1,1),
  TaiKhoan VARCHAR(255) NOT NULL UNIQUE,
  MatKhau VARCHAR(255) NOT NULL,
  PhanQuyen VARCHAR(10) NOT NULL
);
GO

CREATE TABLE NGUOIDUNG(
    ID_NguoiDung INT PRIMARY KEY IDENTITY(1,1),
    HoTen NVARCHAR(50) NOT NULL,
    GioiTinh INT NOT NULL,
    NgaySinh DATE NOT NULL,
    DiaChi NVARCHAR(50),
    SDT CHAR(10) NOT NULL,
    AnhDaiDien VARBINARY(MAX),
    Email VARCHAR(50), 
    MoTaCaNhan NVARCHAR(255),
    ID_DangNhap INT NOT NULL REFERENCES THONGTINDANGNHAP(ID_DangNhap)
)
GO

CREATE TABLE QUANTRIVIEN(
    ID_QuanTri INT PRIMARY KEY IDENTITY(1,1),
    HoTen NVARCHAR(50) NOT NULL,
    ID_DangNhap INT NOT NULL REFERENCES THONGTINDANGNHAP(ID_DangNhap)
)
GO

CREATE TABLE BAIVIET(
    ID_BaiViet INT PRIMARY KEY IDENTITY(1,1),
    NoiDung NVARCHAR(255),
    HinhAnh VARBINARY(MAX),
    ThoiGianDang DATETIME NOT NULL,
    SLThich INT DEFAULT 0,
    ID_NguoiDung INT NOT NULL REFERENCES NGUOIDUNG(ID_NguoiDung)
)
GO

CREATE TABLE TINNHAN(
    ID_TinNhan INT PRIMARY KEY IDENTITY(1,1),
    NoiDung NVARCHAR(255),
    HinhAnh VARBINARY(MAX),
    ThoiGianGui DATETIME NOT NULL,
    TrangThai INT DEFAULT 1,
    ID_NguoiGui INT NOT NULL REFERENCES NGUOIDUNG(ID_NguoiDung),
    ID_NguoiNhan INT NOT NULL REFERENCES NGUOIDUNG(ID_NguoiDung)
)
GO

CREATE TABLE GHEPDOI(
    ID_GhepDoi INT PRIMARY KEY IDENTITY(1,1),
    ID_NguoiDung1 INT NOT NULL REFERENCES NGUOIDUNG(ID_NguoiDung),
    ID_NguoiDung2 INT NOT NULL REFERENCES NGUOIDUNG(ID_NguoiDung),
    ThoiGianGhepDoi DATETIME NOT NULL,
    BieuTuongDoi VARBINARY(MAX)
)
GO

CREATE TABLE KETBAN(
    ID_KetBan INT PRIMARY KEY IDENTITY(1,1),
    ID_NguoiDung1 INT NOT NULL REFERENCES NGUOIDUNG(ID_NguoiDung),
    ID_NguoiDung2 INT NOT NULL REFERENCES NGUOIDUNG(ID_NguoiDung),
    ThoiGianKetBan DATETIME NOT NULL
)
GO

CREATE TABLE THICHBAIVIET(
    ID_ThichBaiViet INT PRIMARY KEY IDENTITY(1,1),
    ID_BaiViet INT NOT NULL REFERENCES BAIVIET(ID_BaiViet),
    ID_NguoiDung INT NOT NULL REFERENCES NGUOIDUNG(ID_NguoiDung)
)
GO

CREATE TABLE BAOCAO(
    ID_BaoCao INT PRIMARY KEY IDENTITY(1,1),
    ID_NguoiDung INT NOT NULL REFERENCES NGUOIDUNG(ID_NguoiDung),
    ID_BaiViet INT NOT NULL REFERENCES BAIVIET(ID_BaiViet),
    ID_QuanTri INT REFERENCES QUANTRIVIEN(ID_QuanTri),
    ThoiGianBaoCao DATETIME NOT NULL,
    NoiDungBaoCao NVARCHAR(255) NOT NULL,
    ThoiGianPhanHoi DATETIME,
    NoiDungPhanHoi NVARCHAR(255)
)
GO

CREATE TABLE SOTHICH(
    ID_SoThich INT PRIMARY KEY IDENTITY(1,1),
    TenSoThich NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE SOTHICH_NGUOIDUNG(
    ID_NguoiDung INT NOT NULL REFERENCES NGUOIDUNG(ID_NguoiDung),
    ID_SoThich INT NOT NULL REFERENCES SOTHICH(ID_SoThich),
    PRIMARY KEY(ID_NguoiDung, ID_SoThich)
)
GO







